departments_list = ["AFID Rawalpindi",
"Agriculture",
"AJK",
"Banks",
"Bazm-e-Iqbal",
"CAA",
"Cantonement Board",
"City District Government",
"Civil Defense",
"Communication & Works Department",
"Construction & Development",
"Currency Exchange Rates",
"Development Authority",
"District Government",
"District Munciple Administration",
"Education",
"Employees Social Security Institution",
"Excise & Taxation",
"FATA",
"FBR",
"Federal Government of Pakistan",
"Forest Division",
"Gilgit Baltistan Environmental Protection Agency",
"Government of Balochistan",
"Government of Gilgit Baltistan",
"Government of Gilgit Baltistan",
"Government of Khyber Pakhtunkhawa",
"Government of Pakistan",
"Government of Punjab",
"Government of Sindh",
"Gwadar Port Authority(GPA)",
"Health",
"Highway Division",
"Housing Authorities",
"Housing Society",
"International Agencies",
"Irrigation & Power Deptt.",
"LDA",
"Livestock",
"Ministry of Ports & Shipping",
"Ministry of Science & Technology",
"Municipal Committee of Chasherif",
"Office of the District Co-ordination",
"Oil & Gas Development Corp.",
"P. O. Box",
"P.O.Box1191 GPO Islamabad",
"Pakistan Defense",
"Pakistan Housing Authority",
"Pakistan Navy",
"Pakistan Petroleum Limited(PPL)",
"Pakistan Post",
"Pakistan Railways",
"Pakistan State Oil",
"Pakistan Steel",
"Pakistan Television Corporation",
"PARCO",
"PASCO",
"PIA",
"Police",
"Private Sector",
"Provincial Buildings Division",
"Provisional Buildings Department",
"PTCL",
"Public Health Engg.",
"Public Sector",
"Public Works Department",
"Research Centres",
"rural health center",
"Security & Exchange Commission of Pakistan (SECP)",
"Social Security & Social Welfare",
"Standard Charted Bank (Pakiatan) Limited",
"State Bank of Pakistan",
"Sui Northern Gas Pipe Lines Ltd.",
"Sui Southern Gas Company Ltd.",
"SUPARCO",
"UC 38,Fateh Jang,TMA,Attock",
"WAPDA",
"WASA",
"Works & Services Department"
]
categories = [

    "Addition & Alteration",
"Advertising",
"Agriculture",
"Air Conditioning",
"Arms Ammunition",
"Auction",
"Audio Visual",
"Auto Parts",
"Automobiles/Vehicles",
"Baldia",
"Bank Auctions",
"Bi Cycles Required",
"Bridges",
"Buildings",
"Cables",
"Chemicals",
"CNG Kits",
"Communication & Works",
"Computers/Accessories",
"Construction",
"Consultancy",
"Clothing/Uniform",
"Corrigendum/Addendum",
"Currency Exchange Rates",
"Development Authority",
"Earth Moving Machinery",
"Education",
"Electrical",
"Electronics",
"Energy",
"Engineering",
"Environment",
"Fabrication",
"Fan",
"Fiber",
"Filter",
"Fire",
"Foam",
"Food / Soap etc.",
"Forest",
"Furniture",
"General Order Supply",
"Generators",
"Highways",
"Horticulture",
"Housekeeping Service",
"Hydraulic Machinery",
"Import / Export",
"Insurance",
"Interiors",
"International",
"Irrigation",
"IT",
"Janitorial",
"Labor Required",
"LDA",
"Lifts",
"Light",
"Live Stock",
"Logistics",
"Machinery",
"Material",
"Mechanical",
"Medical & Scientific",
"Motor Cycle",
"Networking",
"NGO / Relief Works",
"NHA",
"OGDCL",
"Oil & Lubricant",
"P.O. Box",
"Paints",
"Passco",
"Pharma",
"Photo Material",
"Pipes",
"Plastic",
"Pre Qualification",
"Private Sector",
"Public Health",
"Pumps",
"PWD",
"Railway",
"Repair & Maintenance",
"Roads",
"Rubber",
"Scrap Material",
"Security",
"Services Required",
"Sewing Machines",
"Software",
"Sports Items",
"Stationery",
"Steel",
"Streets / Soling",
"Telecommunications",
"Textile/Uniform/Shoes",
"Tiles/Marbles",
"Toll Tax",
"Tractor",
"Training Material",
"Transportation",
"Tubewells",
"UPS",
"Veterinary",
"WAPDA",
"WASA",
"Water",
"Water Supply Scheme / Drains / Sewerage",
"Wood/Timber"
]
  


# Define the tender JSON
tender = {
    "Category": "Construction",
    "Title": "Building Bridge",
    "Publish Date": "2024-12-09",
    "Opening Date": "2024-12-15",
    "Depart Name": "Public Works Department",
    "City": "Lahore",
    "Tender Docs": "http://example.com/docs"
}






    


